import assert from "node:assert/strict";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { spawn, spawnSync } from "node:child_process";

process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
const base = process.env.AICRM_DISTRIBUTION_BROWSER_URL;
const distributorSession = process.env.AICRM_DISTRIBUTION_BROWSER_SESSION;
const promotion = process.env.AICRM_DISTRIBUTION_BROWSER_PROMOTION;
const product = process.env.AICRM_DISTRIBUTION_BROWSER_PRODUCT;
const admin = process.env.AICRM_DISTRIBUTION_BROWSER_ADMIN;
const password = process.env.AICRM_DISTRIBUTION_BROWSER_PASSWORD;
if (!/^https:\/\//.test(base || "") || !distributorSession || !promotion || !product || !admin || !password) throw new Error("Distribution Chromium journey environment is incomplete");
const sleep = ms => new Promise(resolve => setTimeout(resolve, ms));
function browser() { for (const item of [process.env.AICRM_CHROMIUM_BINARY, "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome", "google-chrome", "chromium"].filter(Boolean)) if ((item.includes("/") ? spawnSync(item,["--version"],{stdio:"ignore"}) : spawnSync("which",[item],{stdio:"ignore"})).status === 0) return item; throw new Error("Chromium is unavailable"); }
class CDP { constructor(socket) { this.socket=socket; this.id=0; this.pending=new Map(); this.exceptions=[]; this.logs=[]; socket.addEventListener("message", event => { const m=JSON.parse(String(event.data)); if(m.method==="Runtime.exceptionThrown"){ this.exceptions.push(m.params?.exceptionDetails?.exception?.description||m.params?.exceptionDetails?.text||"runtime exception"); return; } if(m.method==="Log.entryAdded"){ this.logs.push(m.params?.entry?.text||"log"); return; } const p=this.pending.get(m.id); if (!p) return; this.pending.delete(m.id); m.error?p.reject(new Error(`CDP ${m.error.code}`)):p.resolve(m.result||{}); }); } call(method, params={}) { return new Promise((resolve,reject)=>{const id=++this.id, timer=setTimeout(()=>{this.pending.delete(id);reject(new Error(`CDP ${method} timed out`));},8000);this.pending.set(id,{resolve:v=>{clearTimeout(timer);resolve(v)},reject});this.socket.send(JSON.stringify({id,method,params}));}); } }
async function endpoint(profile) { for(let i=0;i<160;i++){try { const p=(await fs.readFile(path.join(profile,"DevToolsActivePort"),"utf8")).split("\n")[0]; if(/^\d+$/.test(p))return `http://127.0.0.1:${p}`; }catch{} await sleep(50);} throw new Error("Chromium DevTools did not start"); }
async function value(cdp, expression) { const r=await cdp.call("Runtime.evaluate",{expression,returnByValue:true,awaitPromise:true}); if(r.exceptionDetails) throw new Error("page evaluation failed"); return r.result?.value; }
async function wait(cdp, expression, message) { for(let i=0;i<180;i++){if(await value(cdp,expression))return;await sleep(50);} throw new Error(`${message} exceptions=${JSON.stringify(cdp.exceptions)} logs=${JSON.stringify(cdp.logs)}`); }
async function addCookie(cdp,name,value) { await cdp.call("Network.setCookie",{url:base,name,value,secure:true}); }
async function login(cdp) { const page=await fetch(`${base}/login`,{redirect:"manual"}); const html=await page.text(), csrf=/name="login_csrf_token" value="([^"]+)"/.exec(html)?.[1]; if(!csrf)throw new Error("login CSRF unavailable"); const cookies=(typeof page.headers.getSetCookie==="function"?page.headers.getSetCookie():[]).map(v=>v.split(";",1)[0]).join("; "); const response=await fetch(`${base}/login`,{method:"POST",redirect:"manual",headers:{"Content-Type":"application/x-www-form-urlencoded",Cookie:cookies},body:new URLSearchParams({username:admin,password,login_csrf_token:csrf})}); if(response.status!==303)throw new Error(`admin login status=${response.status}`); for(const raw of response.headers.getSetCookie?.()||[]){const pair=raw.split(";",1)[0], n=pair.indexOf("="); if(n>0)await addCookie(cdp,pair.slice(0,n),pair.slice(n+1));} }

const profile=await fs.mkdtemp(path.join(os.tmpdir(),"aicrm-distribution-chromium-")); let child, cdp;
try {
  child=spawn(browser(),["--headless=new","--no-sandbox","--remote-debugging-port=0",`--user-data-dir=${profile}`,"--ignore-certificate-errors","--allow-insecure-localhost","about:blank"],{stdio:"ignore"});
  const page=await (await fetch(`${await endpoint(profile)}/json/new?about:blank`,{method:"PUT"})).json(); const socket=new WebSocket(page.webSocketDebuggerUrl); await new Promise((resolve,reject)=>{socket.addEventListener("open",resolve,{once:true});socket.addEventListener("error",()=>reject(new Error("CDP connection failed")),{once:true});}); cdp=new CDP(socket); await cdp.call("Page.enable"); await cdp.call("Runtime.enable"); await cdp.call("Log.enable");
  await addCookie(cdp,"aicrm_distribution_session",distributorSession);
  await cdp.call("Page.navigate",{url:`${base}/distribution`}); await sleep(200); await value(cdp,"import(document.querySelector('script')?.src).then(()=>true)"); await wait(cdp,"document.querySelector('#distribution-root')?.textContent.includes('DISTBROWSER01')",`Distribution center did not render real session/read-model facts ${await value(cdp,"(async()=>JSON.stringify({path:location.pathname,text:document.querySelector('#distribution-root')?.textContent||'',script:document.querySelector('script')?.src,asset:await fetch(document.querySelector('script')?.src).then(r=>[r.status,r.headers.get('content-type')]),me:await fetch('/api/v1/distribution/me').then(async r=>[r.status,await r.text()]),products:await fetch('/api/v1/distribution/products?limit=50').then(async r=>[r.status,await r.text()]),earnings:await fetch('/api/v1/distribution/earnings').then(async r=>[r.status,await r.text()]),commissions:await fetch('/api/v1/distribution/commissions?limit=50').then(async r=>[r.status,await r.text()]),ready:document.readyState,scriptType:document.querySelector('script')?.type}))()")}`);
  await value(cdp,"[...document.querySelectorAll('button')].find(x=>x.textContent==='我的收益')?.click(); true"); await wait(cdp,"document.querySelector('#distribution-root')?.textContent.includes('未结算佣金') && document.querySelector('#distribution-root')?.textContent.includes('分销浏览器商品')","Distribution earnings details did not render frozen commission fields"); await cdp.call("Page.navigate",{url:`${base}/d/${promotion}`}); await wait(cdp,`location.pathname==='/p/${product}' && new URLSearchParams(location.search).get('promotion_context')==='${promotion}'`,`/d did not resolve to the target product with its opaque context`); await wait(cdp,"Boolean(document.querySelector('a[href^=\"/pay/\"]'))",`promotion landing did not render checkout link ${await value(cdp,"JSON.stringify({text:document.body.textContent,path:location.pathname,query:location.search,links:[...document.querySelectorAll(\'a\')].map(a=>a.getAttribute(\'href\'))})")}`);
  await value(cdp,"document.querySelector('a[href^=\"/pay/\"]')?.click(); true"); await wait(cdp,`location.pathname==='/pay/${product}' && new URLSearchParams(location.search).get('promotion_context')==='${promotion}'`,`promotion context did not reach checkout page`);
  await cdp.call("Page.navigate",{url:`${base}/p/${product}`}); await wait(cdp,"location.search==='' && Boolean(document.querySelector('a[href^=\"/pay/\"]'))","ordinary product entry did not render"); const directPayment=await value(cdp,"document.querySelector('a[href^=\"/pay/\"]')?.getAttribute('href')"); assert.equal(directPayment,`/pay/${product}`,"ordinary revisit retained promotion attribution");
  await login(cdp); await cdp.call("Page.navigate",{url:`${base}/admin/distribution`}); await sleep(200); await value(cdp,"import(document.querySelector('script')?.src).then(()=>true)"); await wait(cdp,"document.querySelector('#distribution-admin-root')?.textContent.includes('DISTBROWSER01')","Distribution admin distributor view did not read back the real distributor"); await value(cdp,"[...document.querySelectorAll('button')].find(x=>x.textContent==='订单')?.click(); true"); await wait(cdp,"document.querySelector('#distribution-admin-root')?.textContent.includes('分销浏览器商品') && document.querySelector('#distribution-admin-root')?.textContent.includes('order-9001')",`Distribution admin page did not read back the real distributor and frozen order facts ${await value(cdp,"(async()=>JSON.stringify({text:document.querySelector(\'#distribution-admin-root\')?.textContent||document.body.textContent,script:document.querySelector(\'script\')?.src,distributors:await fetch(\'/api/admin/distribution/distributors?limit=50\').then(async r=>[r.status,await r.text()]),orders:await fetch(\'/api/admin/distribution/orders?limit=50\').then(async r=>[r.status,await r.text()])}))()")}`);
  console.log("distribution_chromium: PASS");
} finally { if(cdp)cdp.socket.close(); if(child&&child.exitCode===null){child.kill("SIGTERM");await Promise.race([new Promise(resolve=>child.once("exit",resolve)),sleep(3000)]);if(child.exitCode===null)child.kill("SIGKILL");} await fs.rm(profile,{recursive:true,force:true}).catch(()=>{}); }
