import { openDetailDrawer } from './shared/ui/detailDrawer';
import { renderQr } from '../src/admin/sections/qr';
export {};
type Row = Record<string, unknown>; type Tab = 'distributors'|'orders'|'exceptions';
const root = document.getElementById('distribution-admin-root'); if (!root) throw new Error('分销管理容器缺失'); const distributionRoot: HTMLElement = root;
const obj=(v:unknown):Row=>v!==null&&typeof v==='object'&&!Array.isArray(v)?v as Row:{};
const text=(v:unknown,f='—')=>typeof v==='string'&&v.trim()?v:f;
const num=(v:unknown,f=0)=>Number.isSafeInteger(Number(v))?Number(v):f;
const idText=(v:unknown,f='')=>typeof v==='string'&&v.trim()?v.trim():Number.isSafeInteger(Number(v))&&Number(v)>0?String(Number(v)):f;
const esc=(v:unknown)=>text(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]||c));
const money=(v:unknown,c='CNY')=>Number.isSafeInteger(Number(v))?new Intl.NumberFormat('zh-CN',{style:'currency',currency:c}).format(Number(v)/100):'—';
const qualifyLabel=(v:unknown)=>({eligible:'资格有效',ineligible:'未满足购买资格',suspended:'退款核验中',identity_conflict:'身份关联待核验',evidence_unavailable:'购买凭证待核验'} as Row)[text(v,'')] as string||'资格待确认';
const commissionLabel=(v:unknown)=>({pending:'待结算',held:'暂缓结算',settling:'结算处理中',paid:'已到账',cancelled:'已取消',exception:'异常待处理',zero_commission:'零佣金成交'} as Row)[text(v,'')] as string||'状态待确认';
const settlementLabel=(v:unknown)=>({planned:'待提交',accepted:'已受理',attempted:'处理中',outcome_unknown:'结果待核验',receiver_succeeded:'已确认到账',cancelled:'已取消',exception:'异常待处理'} as Row)[text(v,'')] as string||'状态待确认';
const adjustmentLabel=(v:unknown)=>({buyer_refund:'买家退款调整',qualification_hold:'资格暂缓',qualification_revoke:'资格撤销',qualification_restore:'资格恢复',manual_recovery:'人工追回登记',merchant_liability:'商户承担登记'} as Row)[text(v,'')] as string||'调整待确认';
const exceptionLabel=(v:unknown)=>({settlement_unknown:'结算结果待核验',settlement_not_paid:'分账未到账',settlement_deadline:'结算时限异常',settlement_deadline_imminent:'结算时限提醒',receiver_unavailable:'收款准备未完成',qualification_revoked_after_paid:'资格变化后已付',buyer_refund_after_paid:'退款后已付',unfreeze_final_failed:'解冻失败',merchant_liability:'商户承担',recovery:'追回登记'} as Row)[text(v,'')] as string||'异常待确认';
const reasonLabel=(v:unknown)=>({buyer_refund:'买家退款',buyer_refund_after_paid:'买家退款后已存在已付金额',qualification_refund_evidence_pending:'退款凭证待核验',refund_outcome_pending:'退款结果待核验',settlement_outcome_unknown:'结算结果待核验',split_deadline_within_24h:'结算时限不足 24 小时',payment_receiver_account_abnormal:'接收方账户异常，请核验微信账户状态',payment_receiver_relation_removed:'接收方分账关系已解除，请完成关系核验',payment_receiver_high_risk:'接收方被风控限制，请联系商家核验',payment_receiver_real_name_unverified:'接收方未完成实名认证，请完成后再核验',payment_merchant_permission_revoked:'商户分账权限已解除，请在商户平台核验',payment_receiver_receipt_limit:'接收方收款额度已达上限，请核验额度',payment_payer_account_abnormal:'付款方账户异常，请核验付款方状态',payment_invalid_split_request:'分账请求被拒绝，请核验订单与接收方参数',manual_recovery:'已登记人工追回',merchant_liability:'已登记商户承担'} as Row)[text(v,'')] as string||'原因以处理审计为准';
const displayName=(v:unknown)=>text(v,'').trim()||'未设置昵称';
const receiverStatusLabel=(ready:unknown,reason:unknown,label:unknown)=>text(label,'').trim()||(()=>{if(ready===true)return '收款准备完成';return ({receiver_accepted:'收款申请已受理，等待支付侧确认',receiver_outcome_unknown:'收款结果待支付侧核验',receiver_final_failed:'收款准备失败，需管理员核验支付侧状态',receiver_unavailable:'收款准备不可用，需管理员核验支付侧条件'} as Row)[text(reason,'')] as string||'收款准备待支付侧核验';})();
const auditEventLabel=(v:unknown)=>({'distribution.exception_opened.v1':'已记录异常','distribution.exception_reconciled.v1':'已查询最新结果','distribution.recovery_recorded.v1':'已登记追回','distribution.merchant_liability_recorded.v1':'已登记商户承担'} as Row)[text(v,'')] as string||'已记录处理';
function actorScopeLabel(v:unknown){const scope=text(v,'');if(scope.startsWith('access:'))return '管理员';if(scope.startsWith('worker:distribution-due'))return '系统结算检查';if(scope.startsWith('order-refund:'))return '订单退款处理';return scope?'系统记录':'未记录';}
function csrf(){for(const p of document.cookie.split(';')){const[n,...r]=p.trim().split('=');if(n==='aicrm_csrf'||n==='aicrm_admin_csrf')return decodeURIComponent(r.join('='));}return '';}
function errText(status:number,payload:unknown){const code=obj(payload).error;const labels:Row={conflict:'记录已变化，请重新读取后再处理。',forbidden:'当前管理员无权执行此操作。',permission_denied:'当前管理员无权查看此记录。',unavailable:'服务暂不可用，未执行操作。',invalid_request:'请求参数无效。',not_found:'记录不存在或已不可见。'};return typeof code==='string'&&typeof labels[code]==='string'?labels[code] as string:`请求失败（HTTP ${status}）`;}
const keys=new Map<string,string>(); function key(scope:string){let v=keys.get(scope);if(!v){v=`distribution-admin-${crypto.randomUUID()}`;keys.set(scope,v);}return v;}
async function request(path:string,init:RequestInit={},scope=''):Promise<unknown>{const headers=new Headers(init.headers);headers.set('Accept','application/json');if(init.method&&init.method!=='GET'){headers.set('Content-Type','application/json');const c=csrf();if(c)headers.set('X-CSRF-Token',c);headers.set('Idempotency-Key',scope?key(scope):`distribution-admin-${crypto.randomUUID()}`);}let r:Response;try{r=await fetch(path,{...init,headers,credentials:'same-origin',cache:'no-store'});}catch{throw new Error('网络不可用，未确认任何分销操作。');}const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(errText(r.status,p));return p;}
function button(label:string,run:()=>void|Promise<void>,primary=false){const b=document.createElement('button');b.type='button';b.textContent=label;b.className=`admin-button distribution-button${primary?' admin-button--primary primary':''}`;b.addEventListener('click',()=>void run());return b;}
function notice(v:string,failed=false){const n=document.querySelector<HTMLElement>('[data-distribution-admin-message]');if(n){n.textContent=v;n.dataset.error=String(failed);}}
function fact(label:string,value:string){const n=document.createElement('div');n.className='distribution-detail-fact';n.innerHTML=`<span>${esc(label)}</span><strong>${esc(value)}</strong>`;return n;}
function drawer(title:string){const body=document.createElement('section');body.className='distribution-detail-body';body.textContent='正在读取服务端明细…';openDetailDrawer(title,body);return body;}
function failed(body:HTMLElement,e:unknown){body.replaceChildren(Object.assign(document.createElement('p'),{className:'distribution-error',textContent:e instanceof Error?e.message:'明细读取失败。'}));}
function timeText(v:unknown){const raw=text(v,'');if(!raw)return '未记录';const date=new Date(raw);return Number.isNaN(date.valueOf())?raw:new Intl.DateTimeFormat('zh-CN',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Shanghai',hour12:false}).format(date);}
function recordList(title:string,items:Row[],render:(item:Row)=>HTMLElement){const list=document.createElement('section');list.className='distribution-detail-list';list.append(Object.assign(document.createElement('h3'),{textContent:title}));if(!items.length)list.append(Object.assign(document.createElement('p'),{textContent:'暂无记录。'}));for(const item of items)list.append(render(item));return list;}
function record(facts:[string,string][],open?:()=>void){const entry=document.createElement(open?'button':'div');entry.className='distribution-detail-record';if(entry instanceof HTMLButtonElement){entry.type='button';entry.addEventListener('click',()=>void open?.());}for(const[label,value]of facts)entry.append(fact(label,value));return entry;}
function applicationURL(){return new URL('/distribution',location.origin).toString();}
async function copyApplicationLink(){const url=applicationURL();if(!navigator.clipboard?.writeText){notice('当前环境不支持自动复制，请复制申请页面地址。',true);return;}try{await navigator.clipboard.writeText(url);notice('分销申请链接已复制。');}catch{notice('未能自动复制，请复制申请页面地址。',true);}}
function showApplicationEntry(){const body=document.createElement('section');body.className='distribution-detail-body';const url=applicationURL(),note=document.createElement('p');note.textContent='该入口用于微信可信登录后的分销员注册；商品编辑页的入口会保留对应商品上下文。';const input=document.createElement('input');input.value=url;input.readOnly=true;input.className='distribution-application-link';const qr=document.createElement('div');qr.className='distribution-application-qr';renderQr(qr,url,'分销员申请入口');body.append(note,input,qr,button('复制申请链接',()=>copyApplicationLink(),true));openDetailDrawer('分销申请入口',body);}

let tab:Tab='distributors',rows:Row[]=[],cursor='';
async function load(next=''){notice('正在读取服务端分销管理事实…');try{const p=obj(await request(`/api/admin/distribution/${tab}${next?`?cursor=${encodeURIComponent(next)}`:''}`));if(!Array.isArray(p.items))throw new Error('分销管理列表响应无效');rows=p.items.map(obj);cursor=text(p.next_cursor,'');render();notice('');}catch(e){notice(e instanceof Error?e.message:'分销管理读取失败',true);}}
function render(){distributionRoot.replaceChildren();const head=document.createElement('header');head.className='distribution-head';head.innerHTML='<div><h1>分销管理</h1><p>管理分销员，查看推广订单、佣金和结算记录。</p></div>';const actions=document.createElement('div');actions.className='admin-toolbar';const open=document.createElement('a');open.href='/distribution';open.target='_blank';open.rel='noopener';open.className='admin-button admin-button--secondary';open.textContent='打开申请页';actions.append(open,button('复制申请链接',()=>copyApplicationLink()),button('申请二维码',()=>showApplicationEntry()));head.append(actions);distributionRoot.append(head);const nav=document.createElement('nav');nav.className='distribution-tabs';for(const[v,l]of[['distributors','分销员'],['orders','订单'],['exceptions','异常']]as const){nav.append(button(l,async()=>{tab=v;await load();},tab===v));}distributionRoot.append(nav,tab==='distributors'?distributors():tab==='orders'?orders():exceptions());if(cursor){const f=document.createElement('footer');f.className='distribution-pagination';f.append(button('下一页',()=>load(cursor)));distributionRoot.append(f);}const m=document.createElement('p');m.dataset.distributionAdminMessage='';m.className='distribution-message';distributionRoot.append(m);}
function table(headers:string[],body:string){const v=document.createElement('div');v.className='admin-table-wrap distribution-table-scroll';v.innerHTML=`<table class="admin-table"><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${body}</tbody></table>`;return v;}
function distributors(){const body=rows.map(r=>`<tr><td>${esc(displayName(r.display_name))}</td><td>${esc(r.agreement_version)}</td><td>${r.enabled===true?'启用':'停用'}</td><td>${esc(receiverStatusLabel(r.receiver_ready,r.receiver_status,r.receiver_status_label))}</td><td>${esc(timeText(r.registered_at))}</td><td><span data-actions="${num(r.id,-1)}" data-version="${num(r.version,-1)}"></span></td></tr>`).join('')||'<tr><td colspan="6">暂无分销员记录。完成微信可信登录、同意协议并注册后，记录会出现在这里。</td></tr>';const v=table(['用户昵称','协议','状态','收款状态','注册时间','操作'],body);for(const h of v.querySelectorAll<HTMLElement>('[data-actions]')){const id=num(h.dataset.actions,-1),ver=num(h.dataset.version,-1);if(id<1||ver<1)continue;const enabled=rows.find(r=>num(r.id,-1)===id)?.enabled===true;h.append(button('查看详情',()=>showDistributor(id)),button(enabled?'停用':'启用',()=>setDistributor(id,ver,enabled?'disable':'enable')));}return v;}
function orders(){const body=rows.map(r=>`<tr><td>${esc(r.order_reference)}</td><td>${esc(r.product_name)}</td><td>${esc(displayName(r.distributor_display_name))}</td><td>${esc(qualifyLabel(r.qualification_state))}</td><td>${esc(r.qualification_evidence_reference)}</td><td>版本 ${num(r.policy_version)} · ${(num(r.rate_basis_points)/100).toFixed(2)}% · ${num(r.wait_days)} 天</td><td>${money(r.paid_minor,text(r.currency,'CNY'))}</td><td><span data-order="${num(r.attribution_id,-1)}"></span></td></tr>`).join('')||'<tr><td colspan="8">暂无归因订单记录。</td></tr>';const v=table(['订单','商品','分销员','推广资格','购买凭证','佣金政策','商品实付','详情'],body);for(const h of v.querySelectorAll<HTMLElement>('[data-order]')){const id=num(h.dataset.order,-1);if(id>0)h.append(button('查看详情',()=>showOrder(id)));}return v;}
function exceptions(){const body=rows.map(r=>`<tr><td>${esc(idText(r.exception_id))}</td><td>${esc(displayName(r.distributor_display_name))}</td><td>${esc(r.order_reference)}</td><td>${esc(exceptionLabel(r.kind))}</td><td>尚欠 ${money(r.unpaid_due_minor)}<br>已付 ${money(r.already_paid_minor)}</td><td>${esc(reasonLabel(r.reason))}</td><td><span data-exception="${esc(idText(r.exception_id))}" data-version="${num(r.version,-1)}" data-reconcile="${String(r.can_reconcile===true)}" data-recovery="${String(r.can_record_recovery===true)}" data-liability="${String(r.can_record_merchant_liability===true)}"></span></td></tr>`).join('')||'<tr><td colspan="7">暂无异常记录。</td></tr>';const v=table(['异常','分销员','订单','类型','资金事实','原因','人工处理'],body);for(const h of v.querySelectorAll<HTMLElement>('[data-exception]')){const id=h.dataset.exception||'',ver=num(h.dataset.version,-1);if(!id||ver<1)continue;h.append(button('查看详情',()=>showException(id)));if(h.dataset.reconcile==='true')h.append(button('查询最新结果',()=>reconcile(id,ver)));if(h.dataset.recovery==='true')h.append(button('登记追回',()=>recovery(id,ver)));if(h.dataset.liability==='true')h.append(button('登记商户承担',()=>liability(id,ver)));}return v;}
function distributorOrdersList(distributorID:number, first:Row){const list=document.createElement('div');list.className='distribution-detail-list';list.append(Object.assign(document.createElement('h3'),{textContent:'关联推广订单'}));const seen=new Set<string>();const append=(page:Row)=>{const items=Array.isArray(page.items)?page.items.map(obj):null;if(!items)throw new Error('关联推广订单响应无效');for(const item of items){const attributionID=idText(item.attribution_id);if(!attributionID||seen.has(attributionID))continue;seen.add(attributionID);list.append(button(`${text(item.order_reference)} · ${text(item.product_name)}`,()=>showOrder(num(item.attribution_id,-1))));}if(!seen.size)list.append(Object.assign(document.createElement('p'),{textContent:'暂无归因订单。'}));const next=text(page.next_cursor,'');if(!next)return;const more=button('加载更多订单',async()=>{more.disabled=true;more.textContent='正在读取更多订单…';try{const page= obj(await request(`/api/admin/distribution/distributors/${distributorID}/orders?limit=10&cursor=${encodeURIComponent(next)}`));more.remove();list.querySelector('[data-distribution-more-error]')?.remove();append(page);}catch(e){more.disabled=false;more.textContent='重试读取更多订单';let feedback=list.querySelector<HTMLElement>('[data-distribution-more-error]');if(!feedback){feedback=document.createElement('p');feedback.dataset.distributionMoreError='';feedback.className='distribution-error';list.append(feedback);}feedback.textContent=`读取更多关联订单失败：${e instanceof Error?e.message:'请重试。'}`;}});list.append(more);};append(first);return list;}
async function showDistributor(id:number){const b=drawer('分销员详情');try{const[d,o]=await Promise.all([request(`/api/admin/distribution/distributors/${id}`),request(`/api/admin/distribution/distributors/${id}/orders?limit=10`)]);const x=obj(d),r=obj(x.distributor),e=obj(x.earnings),orders=obj(o),grid=document.createElement('div');grid.className='distribution-detail-grid';grid.append(fact('用户昵称',displayName(r.display_name)),fact('分销编号',text(r.public_no,'未提供')),fact('协议版本',text(r.agreement_version)),fact('注册时间',timeText(r.registered_at)),fact('状态',r.enabled===true?'启用':'停用'),fact('收款状态',receiverStatusLabel(r.receiver_ready,r.receiver_status,r.receiver_status_label)),fact('推广成交',money(e.gross_paid_sales_minor,text(e.currency,'CNY'))),fact('累计退款',money(e.successful_refunds_minor,text(e.currency,'CNY'))),fact('初始佣金',money(e.initial_commission_minor,text(e.currency,'CNY'))),fact('佣金调整',money(e.commission_adjustments_minor,text(e.currency,'CNY'))),fact('当前待付',money(e.unsettled_payable_minor,text(e.currency,'CNY'))),fact('确认到账',money(e.paid_commission_minor,text(e.currency,'CNY'))),fact('已追回',money(e.recovered_minor,text(e.currency,'CNY'))));b.replaceChildren(grid,distributorOrdersList(id,orders));}catch(e){failed(b,e);}}
async function showOrder(id:number){const b=drawer('推广订单详情');try{const x=obj(await request(`/api/admin/distribution/orders/${id}`)),o=obj(x.order),c=obj(x.commission),grid=document.createElement('div');grid.className='distribution-detail-grid';grid.append(fact('订单',text(o.order_reference)),fact('商品',text(o.product_name)),fact('分销员',displayName(o.distributor_display_name)),fact('推广资格',qualifyLabel(o.qualification_state)),fact('购买凭证',text(o.qualification_evidence_reference)),fact('佣金政策',`版本 ${num(o.policy_version)} · ${(num(o.rate_basis_points)/100).toFixed(2)}% · ${num(o.wait_days)} 天`),fact('商品实付',money(o.paid_minor,text(o.currency,'CNY'))));if(Object.keys(c).length)grid.append(fact('佣金状态',commissionLabel(c.status)),fact('初始佣金',money(c.initial_minor,text(c.currency,'CNY'))),fact('累计退款',money(c.successful_refund_minor,text(c.currency,'CNY'))),fact('当前应付',money(c.current_payable_minor,text(c.currency,'CNY'))),fact('确认到账',money(c.paid_minor,text(c.currency,'CNY'))),fact('订单支付确认',timeText(c.paid_confirmed_at)),fact('预计结算时间',timeText(c.due_at)));const adjustments=Array.isArray(x.adjustments)?x.adjustments.map(obj):[],settlements=Array.isArray(x.settlements)?x.settlements.map(obj):[],exceptions=Array.isArray(x.exceptions)?x.exceptions.map(obj):[];b.replaceChildren(grid,recordList('退款与资格调整',adjustments,item=>record([['类型',adjustmentLabel(item.kind)],['变动金额',money(item.delta_minor)],['调整后应付',money(item.resulting_payable_minor)],['原因',reasonLabel(item.reason)],['凭证参考',text(item.source_reference)],['发生时间',timeText(item.occurred_at)]])),recordList('结算记录',settlements,item=>record([['结算单',text(item.reference)],['金额',money(item.amount_minor,text(item.currency,'CNY'))],['状态',settlementLabel(item.state)],['最晚结算时间',timeText(item.provider_deadline_at)],['创建时间',timeText(item.created_at)],['最近更新时间',timeText(item.updated_at)]])),recordList('关联异常',exceptions,item=>record([['异常',idText(item.exception_id)],['类型',exceptionLabel(item.kind)],['金额',money(item.amount_minor)],['原因',reasonLabel(item.reason)],['更新时间',timeText(item.updated_at)]],()=>showException(idText(item.exception_id)))));}catch(e){failed(b,e);}}
async function showException(id:string){const b=drawer('异常详情');try{const x=obj(await request(`/api/admin/distribution/exceptions/${encodeURIComponent(id)}`)),grid=document.createElement('div');grid.className='distribution-detail-grid';grid.append(fact('异常',idText(x.exception_id)),fact('分销员',displayName(x.distributor_display_name)),fact('订单',text(x.order_reference)),fact('类型',exceptionLabel(x.kind)),fact('状态',text(x.status)==='open'?'待处理':text(x.status)==='resolved'?'已处理':text(x.status)==='recovery_recorded'?'已登记追回':text(x.status)==='merchant_liability_recorded'?'已登记商户承担':'状态待确认'),fact('尚欠应付',money(x.unpaid_due_minor)),fact('已付事实',money(x.already_paid_minor)),fact('原因',reasonLabel(x.reason)),fact('凭证参考',text(x.evidence_reference)),fact('处理来源',actorScopeLabel(x.actor_scope)),fact('创建时间',timeText(x.created_at)),fact('更新时间',timeText(x.updated_at)));const audit=Array.isArray(x.audit)?x.audit.map(obj):[];b.replaceChildren(grid,recordList('处理审计',audit,item=>record([['处理',auditEventLabel(item.event_type)],['处理来源',actorScopeLabel(item.actor_scope)],['金额',money(item.amount_minor)],['原因',reasonLabel(item.reason)],['凭证参考',text(item.evidence_reference)],['处理时间',timeText(item.occurred_at)]])));}catch(e){failed(b,e);}}
async function mutate(scope:string,path:string,body:string){try{await request(path,{method:'POST',body},scope);keys.delete(scope);await load();}catch(e){await load();notice(`提交结果未确认，已读取最新服务端记录：${e instanceof Error?e.message:'请核对后再操作。'}`,true);}}
async function setDistributor(id:number,version:number,op:'disable'|'enable'){const reason=op==='disable'?window.prompt('停用原因（将记录审计）：')||'':'管理员恢复';if(!reason.trim()){notice('必须填写停用原因，未提交操作。',true);return;}await mutate(`distributor:${op}:${id}:${version}:${reason}`,`/api/admin/distribution/distributors/${id}/${op}`,JSON.stringify({version,reason}));}
async function reconcile(id:string,version:number){await mutate(`reconcile:${id}:${version}`,`/api/admin/distribution/exceptions/${encodeURIComponent(id)}/reconcile`,JSON.stringify({version}));}
function amount(v:string|null){if(!/^\d+$/.test(v||''))return;const n=Number(v);return Number.isSafeInteger(n)&&n>0?n:undefined;}
async function recovery(id:string,version:number){const n=amount(window.prompt('追回金额（分）：')),e=window.prompt('追回凭证参考：');if(n===undefined||!e?.trim()){notice('追回金额必须是有效正整数分，且必须填写凭证参考；未提交操作。',true);return;}await mutate(`recovery:${id}:${version}:${n}:${e.trim()}`,`/api/admin/distribution/exceptions/${encodeURIComponent(id)}/recoveries`,JSON.stringify({version,amount_minor:n,evidence_reference:e.trim()}));}
async function liability(id:string,version:number){const n=amount(window.prompt('商户承担金额（分）：')),r=window.prompt('承担原因：');if(n===undefined||!r?.trim()){notice('承担金额必须是有效正整数分，且必须填写原因；未提交操作。',true);return;}await mutate(`liability:${id}:${version}:${n}:${r.trim()}`,`/api/admin/distribution/exceptions/${encodeURIComponent(id)}/merchant-liabilities`,JSON.stringify({version,amount_minor:n,reason:r.trim()}));}
void load();
