// This browser entry is independently bundled by the host-adapter build.  Mark
// it as an ES module so the repository-wide TypeScript check does not merge its
// private helpers into the public distribution-center entry's global scope.
export {};

type Row = Record<string, unknown>;
type AdminTab = 'distributors' | 'orders' | 'exceptions';
const rootElement = document.getElementById('distribution-admin-root');
if (!rootElement) throw new Error('分销管理容器缺失');
const root: HTMLElement = rootElement;

const obj = (value: unknown): Row => value !== null && typeof value === 'object' && !Array.isArray(value) ? value as Row : {};
const text = (value: unknown, fallback = '—'): string => typeof value === 'string' && value.trim() ? value : fallback;
const number = (value: unknown, fallback = 0): number => Number.isSafeInteger(Number(value)) ? Number(value) : fallback;
const escape = (value: unknown): string => text(value).replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char] || char));
function money(value: unknown, currency = 'CNY'): string { const minor = Number(value); return Number.isSafeInteger(minor) ? new Intl.NumberFormat('zh-CN', { style: 'currency', currency }).format(minor / 100) : '—'; }
function csrf(): string { for (const part of document.cookie.split(';')) { const [name, ...rest] = part.trim().split('='); if (name === 'aicrm_csrf' || name === 'aicrm_admin_csrf') return decodeURIComponent(rest.join('=')); } return ''; }
function errorText(status: number, payload: unknown): string { const code = obj(payload).error; const labels: Record<string, string> = { conflict: '记录已变化，请重新读取后再处理。', forbidden: '当前管理员无权执行此操作。', unavailable: '服务暂不可用，未执行操作。', invalid_request: '提交内容无效，未执行操作。', not_found: '记录不存在或已不可见。' }; return typeof code === 'string' && labels[code] ? labels[code] : `请求失败（HTTP ${status}）`; }
const mutationKeys = new Map<string, string>();
function mutationKey(scope: string): string { let key = mutationKeys.get(scope); if (!key) { key = `distribution-admin-${crypto.randomUUID()}`; mutationKeys.set(scope, key); } return key; }
async function request(path: string, init: RequestInit = {}, keyScope = ''): Promise<unknown> { const headers = new Headers(init.headers); headers.set('Accept', 'application/json'); if (init.method && init.method !== 'GET') { headers.set('Content-Type', 'application/json'); const token = csrf(); if (token) headers.set('X-CSRF-Token', token); headers.set('Idempotency-Key', keyScope ? mutationKey(keyScope) : `distribution-admin-${crypto.randomUUID()}`); } let response: Response; try { response = await fetch(path, { ...init, headers, credentials: 'same-origin', cache: 'no-store' }); } catch { throw new Error('网络不可用，未确认任何分销操作。'); } const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(errorText(response.status, payload)); return payload; }
async function mutate(scope: string, path: string, body: string): Promise<void> { try { await request(path, { method: 'POST', body }, scope); mutationKeys.delete(scope); await load(); } catch (error) { await load(); notice(`提交结果未确认，已读取最新服务端记录：${error instanceof Error ? error.message : '请核对后再操作。'}`, true); } }
function button(label: string, run: () => void | Promise<void>, primary = false): HTMLButtonElement { const element = document.createElement('button'); element.type = 'button'; element.textContent = label; element.className = `distribution-button${primary ? ' primary' : ''}`; element.addEventListener('click', () => void run()); return element; }
function notice(message: string, failed = false): void { const element = document.querySelector<HTMLElement>('[data-distribution-admin-message]'); if (element) { element.textContent = message; element.dataset.error = String(failed); } }

let tab: AdminTab = 'distributors'; let rows: Row[] = []; let cursor = '';
async function load(next = ''): Promise<void> { notice('正在读取服务端分销管理事实…'); try { const path = `/api/admin/distribution/${tab}${next ? `?cursor=${encodeURIComponent(next)}` : ''}`; const payload = obj(await request(path)); if (!Array.isArray(payload.items)) throw new Error('分销管理列表响应无效'); rows = payload.items.map(obj); cursor = text(payload.next_cursor, ''); render(); notice(''); } catch (error) { notice(error instanceof Error ? error.message : '分销管理读取失败', true); } }
function render(): void { root.replaceChildren(); const title = document.createElement('header'); title.className = 'distribution-head'; title.innerHTML = '<div><h1>分销管理</h1><p>仅展示服务端归因、佣金、结算和人工处理审计事实。</p></div>'; root.append(title); const nav = document.createElement('nav'); nav.className = 'distribution-tabs'; for (const [value, label] of [['distributors', '分销员'], ['orders', '订单'], ['exceptions', '异常']] as const) { const node = button(label, async () => { tab = value; await load(); }); node.classList.toggle('active', tab === value); nav.append(node); } root.append(nav, tableForTab()); const footer = document.createElement('footer'); footer.className = 'distribution-pagination'; if (cursor) footer.append(button('下一页', () => load(cursor))); root.append(footer); const message = document.createElement('p'); message.dataset.distributionAdminMessage = ''; message.className = 'distribution-message'; root.append(message); }
function table(headers: string[], body: string): HTMLElement { const scroll = document.createElement('div'); scroll.className = 'distribution-table-scroll'; scroll.innerHTML = `<table><thead><tr>${headers.map((header) => `<th>${escape(header)}</th>`).join('')}</tr></thead><tbody>${body}</tbody></table>`; return scroll; }
function tableForTab(): HTMLElement { if (tab === 'distributors') return distributorsTable(); if (tab === 'orders') return ordersTable(); return exceptionsTable(); }
function distributorsTable(): HTMLElement { const tbody = rows.map((row) => `<tr><td>${escape(row.public_no)}</td><td>${escape(row.customer_reference)}</td><td>${escape(row.agreement_version)}</td><td>${row.enabled === true ? '启用' : '停用'}</td><td>${row.receiver_ready === true ? '已就绪' : escape(row.receiver_reason)}</td><td>${escape(row.registered_at)}</td><td><span data-distributor-actions="${number(row.id, -1)}" data-version="${number(row.version, -1)}"></span></td></tr>`).join('') || '<tr><td colspan="7">暂无分销员记录。</td></tr>'; const view = table(['编号', '客户参考', '协议', '状态', '收款准备', '注册时间', '操作'], tbody); for (const host of view.querySelectorAll<HTMLElement>('[data-distributor-actions]')) { const id = number(host.dataset.distributorActions, -1); const version = number(host.dataset.version, -1); if (id < 1 || version < 1) continue; const enabled = rows.find((row) => number(row.id, -1) === id)?.enabled === true; host.append(button(enabled ? '停用' : '启用', () => setDistributor(id, version, enabled ? 'disable' : 'enable'))); } return view; }
async function setDistributor(id: number, version: number, operation: 'disable' | 'enable'): Promise<void> { const reason = operation === 'disable' ? window.prompt('停用原因（将记录审计）：') || '' : '管理员恢复'; if (!reason.trim()) { notice('必须填写停用原因，未提交操作。', true); return; } await mutate(`distributor:${operation}:${id}:${version}:${reason}`, `/api/admin/distribution/distributors/${id}/${operation}`, JSON.stringify({ version, reason })); }
function ordersTable(): HTMLElement { const tbody = rows.map((row) => `<tr><td>${escape(row.order_reference)}</td><td>${escape(row.item_line)}</td><td>${escape(row.product_name)}</td><td>${escape(row.distributor_public_no)}</td><td>${escape(row.qualification_state)}</td><td>${escape(row.qualification_evidence_reference)}</td><td>v${number(row.policy_version)} · ${(number(row.rate_basis_points) / 100).toFixed(2)}% · ${number(row.wait_days)}天</td><td>${money(row.paid_minor, text(row.currency, 'CNY'))}</td><td>${escape(row.attributed_at)}</td></tr>`).join('') || '<tr><td colspan="9">暂无归因订单记录。</td></tr>'; return table(['订单', '商品项', '商品', '分销员', '资格', '购买证据', '冻结政策', '商品实付', '归因时间'], tbody); }
function exceptionsTable(): HTMLElement { const tbody = rows.map((row) => `<tr><td>${escape(row.exception_id)}</td><td>${escape(row.distributor_public_no)}</td><td>${escape(row.order_reference)}</td><td>${escape(row.kind)} · ${escape(row.status)}</td><td>尚欠 ${money(row.unpaid_due_minor)}<br>已付 ${money(row.already_paid_minor)}</td><td>${escape(row.reason)}</td><td>${escape(row.payment_instruction_reference)}</td><td><span data-exception-actions="${escape(row.exception_id)}" data-version="${number(row.version, -1)}" data-reconcile="${String(row.can_reconcile === true)}" data-recovery="${String(row.can_record_recovery === true)}" data-liability="${String(row.can_record_merchant_liability === true)}"></span></td></tr>`).join('') || '<tr><td colspan="8">暂无异常记录。</td></tr>'; const view = table(['异常', '分销员', '订单', '类型 / 状态', '资金事实', '原因', 'Payment 指令', '人工处理'], tbody); for (const host of view.querySelectorAll<HTMLElement>('[data-exception-actions]')) { const id = host.dataset.exceptionActions || ''; const version = number(host.dataset.version, -1); if (!id || version < 1) continue; if (host.dataset.reconcile === 'true') host.append(button('查询最新结果', () => reconcile(id, version))); if (host.dataset.recovery === 'true') host.append(button('登记追回', () => recovery(id, version))); if (host.dataset.liability === 'true') host.append(button('登记商户承担', () => liability(id, version))); } return view; }
async function reconcile(id: string, version: number): Promise<void> { await mutate(`reconcile:${id}:${version}`, `/api/admin/distribution/exceptions/${encodeURIComponent(id)}/reconcile`, JSON.stringify({ version })); }
function amountMinor(value: string | null): number | undefined { if (!/^\d+$/.test(value || '')) return undefined; const parsed = Number(value); return Number.isSafeInteger(parsed) && parsed > 0 ? parsed : undefined; }
async function recovery(id: string, version: number): Promise<void> { const amount = amountMinor(window.prompt('追回金额（分）：')); const evidence = window.prompt('追回凭证参考：'); if (amount === undefined || !evidence?.trim()) { notice('追回金额必须是有效正整数分，且必须填写凭证参考；未提交操作。', true); return; } await mutate(`recovery:${id}:${version}:${amount}:${evidence.trim()}`, `/api/admin/distribution/exceptions/${encodeURIComponent(id)}/recoveries`, JSON.stringify({ version, amount_minor: amount, evidence_reference: evidence.trim() })); }
async function liability(id: string, version: number): Promise<void> { const amount = amountMinor(window.prompt('商户承担金额（分）：')); const reason = window.prompt('承担原因：'); if (amount === undefined || !reason?.trim()) { notice('承担金额必须是有效正整数分，且必须填写原因；未提交操作。', true); return; } await mutate(`liability:${id}:${version}:${amount}:${reason.trim()}`, `/api/admin/distribution/exceptions/${encodeURIComponent(id)}/merchant-liabilities`, JSON.stringify({ version, amount_minor: amount, reason: reason.trim() })); }

void load();
