import assert from 'node:assert/strict';
import { fileURLToPath } from 'node:url';
import { JSDOM } from 'jsdom';
import { buildTestBrowserBundle } from '../scripts/test-browser-bundle.mjs';

const bundle = await buildTestBrowserBundle(fileURLToPath(new URL('./referralAdmin.ts', import.meta.url)));
const delay = (ms = 8) => new Promise((resolve) => setTimeout(resolve, ms));
async function waitFor(check, description) { for (let index = 0; index < 150; index++) { if (check()) return; await delay(); } throw new Error(description); }
const json = (body, status = 200) => new Response(JSON.stringify(body), { status, headers: { 'Content-Type': 'application/json' } });
const campaign = { id: 7, name: '秋日组队赛', state: 'draft', effective_state: 'draft', version: 3, starts_at: '2026-09-20T00:00:00Z', ends_at: '2026-10-01T00:00:00Z', description: '活动介绍', reward_rules: '奖励规则', cover_url: 'https://cdn.example/cover.png', participant_count: 4, invitation_count: 3, team_count: 1 };
const calls = [];
const dom = new JSDOM('<!doctype html><main id="referral-admin-root"></main>', { url: 'https://crm.example/admin/referral', runScripts: 'outside-only', pretendToBeVisual: true, beforeParse(window) {
  window.Response = Response; window.Headers = Headers; window.URL = URL;
  window.HTMLDialogElement.prototype.showModal = function () { this.setAttribute('open', ''); };
  window.HTMLDialogElement.prototype.close = function () { this.removeAttribute('open'); this.dispatchEvent(new window.Event('close')); };
  window.fetch = async (input, init = {}) => { const url = new URL(String(input), window.location.href); calls.push({ path: url.pathname, query: url.search, method: String(init.method || 'GET'), body: String(init.body || '') });
    if (url.pathname === '/api/admin/referral/campaigns' && (!init.method || init.method === 'GET')) return json({ items: [campaign], next_cursor: '' });
    if (url.pathname === '/api/admin/referral/campaigns/7/state') return json({ ...campaign, state: 'active', version: 4 });
    if (url.pathname === '/api/admin/referral/campaigns/7' && init.method === 'PUT') return json({ ...campaign, cover_url: 'https://cdn.example/cover.png' });
    if (url.pathname === '/api/admin/referral/campaigns/7') return json({ ...campaign, teams: [], daily_metrics: [{ date: '2026-09-20', participant_count: 2, invitation_count: 1 }] });
    if (url.pathname === '/api/admin/customers') return json({ items: [{ customer_id: 101, display_name: '可信客户' }] });
    if (url.pathname === '/api/admin/referral/campaigns/7/teams') return json({ id: 3, name: '冲刺队' }, 201);
    if (url.pathname === '/api/admin/referral/referrals') return json({ items: [{ participation_id: 11, participant_name: '无来源参与者', inviter_name: '', joined_at: '2026-09-20T00:00:00Z', score_state: 'none' }, { participation_id: 12, participant_name: '有效邀请参与者', inviter_name: '邀请人', joined_at: '2026-09-20T00:00:00Z', score_state: 'valid' }] });
    if (url.pathname === '/api/admin/referral/participations/12/reverse') return new Response(null, { status: 204 });
    if (url.pathname === '/api/admin/referral/relationship-history') return json({ items: [{ customer_name: '可信客户', previous_referrer_name: '甲', referrer_name: '乙', accepted_at: '2026-09-20T00:00:00Z' }] });
    if (url.pathname === '/api/admin/referral/rewards' && (!init.method || init.method === 'GET')) return json({ items: [{ customer_name: '可信客户', reward: '奖品', period: 'week:2026-W38', state: 'needs_review', recorded_at: '2026-09-20T00:00:00Z', evidence_reference: 'proof-1' }] });
    if (url.pathname === '/api/admin/referral/rewards' && init.method === 'POST') return json({ reward_id: 9, state: 'recorded' }, 201);
    return json({ error: 'not_found' }, 404);
  };
} });
dom.window.eval(bundle);
await waitFor(() => dom.window.document.body.textContent.includes('秋日组队赛'), 'admin campaign list did not render');
[...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '查看配置').click();
const config = dom.window.document.querySelector('[data-testid="referral-admin-dialog"]');
const configInputs = config.querySelectorAll('input');
assert.equal(configInputs[1].value, 'https://cdn.example/cover.png', 'campaign edit must retain the existing cover URL');
assert.equal(configInputs[2].value, '2026-09-20T08:00', 'campaign datetime-local fields must use Beijing local time');
[...config.querySelectorAll('button')].find((button) => button.textContent === '保存配置').click();
await waitFor(() => calls.some((call) => call.path === '/api/admin/referral/campaigns/7' && call.method === 'PUT'), 'campaign configuration update did not call the real endpoint');
const campaignUpdate = JSON.parse(calls.find((call) => call.path === '/api/admin/referral/campaigns/7' && call.method === 'PUT').body);
assert.equal(campaignUpdate.cover_url, 'https://cdn.example/cover.png', 'campaign update must preserve its cover URL');
assert.equal(campaignUpdate.starts_at, '2026-09-20T00:00:00.000Z', 'a Beijing datetime-local start must be saved in its Beijing instant');
assert.equal(campaignUpdate.ends_at, '2026-10-01T00:00:00.000Z', 'a Beijing datetime-local end must be saved in its Beijing instant');
await waitFor(() => !dom.window.document.querySelector('[data-testid="referral-admin-dialog"]'), 'campaign configuration dialog did not close after an acknowledged write');
dom.window.document.querySelector('[data-testid="referral-admin-publish"]').click();
await waitFor(() => calls.some((call) => call.path.endsWith('/campaigns/7/state')), 'publish control did not call state endpoint');
const publish = calls.find((call) => call.path.endsWith('/campaigns/7/state'));
assert.deepEqual(JSON.parse(publish.body), { expected_version: 3, target: 'active' }, 'publication needs optimistic version and explicit state');
const teamTab = [...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '战队'); teamTab.click();
await waitFor(() => dom.window.document.querySelector('[data-testid="referral-admin-campaign-select"]'), 'team view did not render campaign selector');
const select = dom.window.document.querySelector('[data-testid="referral-admin-campaign-select"]'); select.value = '7'; select.dispatchEvent(new dom.window.Event('change', { bubbles: true }));
await waitFor(() => dom.window.document.querySelector('[data-testid="referral-admin-create-team"]'), 'team create action did not render');
dom.window.document.querySelector('[data-testid="referral-admin-create-team"]').click();
const dialog = dom.window.document.querySelector('[data-testid="referral-admin-dialog"]');
const fields = dialog.querySelectorAll('input'); fields[0].value = '冲刺队'; fields[2].value = '可信'; [...dialog.querySelectorAll('button')].find((button) => button.textContent === '搜索客户').click();
await waitFor(() => dialog.textContent.includes('可信客户'), 'customer picker did not use customer directory');
[...dialog.querySelectorAll('button')].find((button) => button.textContent === '可信客户').click();
[...dialog.querySelectorAll('button')].find((button) => button.textContent === '创建战队').click();
await waitFor(() => calls.some((call) => call.path.endsWith('/campaigns/7/teams') && call.method === 'POST'), 'team creation did not call actual Referral endpoint');
const teamWrite = calls.find((call) => call.path.endsWith('/campaigns/7/teams') && call.method === 'POST');
assert.deepEqual(JSON.parse(teamWrite.body), { name: '冲刺队', logo_url: '', captain_customer_id: 101 }, 'team command must use a selected canonical customer, not typed identity');
assert.match(dom.window.document.querySelector('[data-testid="referral-admin-daily-metrics"]')?.textContent || '', /2026-09-20：参与 2，有效邀请 1/, 'team campaign detail must show daily participant and valid-invitation changes');
const historyReads = calls.filter((call) => call.path === '/api/admin/referral/campaigns').length;
const historyTab = [...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '归属历史'); historyTab.click();
await waitFor(() => calls.filter((call) => call.path === '/api/admin/referral/campaigns').length > historyReads, 'history must refresh campaigns before resolving its picker');
await delay();
await waitFor(() => dom.window.document.body.textContent.includes('请从客户目录选择客户后查看归属历史。'), 'history must be available without selecting a campaign');
const historySearch = dom.window.document.querySelector('.referral-admin-picker input[type=search]'); historySearch.value = '可信'; [...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '搜索客户').click();
await waitFor(() => [...dom.window.document.querySelectorAll('button')].some((button) => button.textContent === '可信客户'), 'history customer picker did not return directory entries');
[...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '可信客户').click();
dom.window.document.querySelector('[data-testid="referral-admin-read-history"]').click();
await waitFor(() => calls.some((call) => call.path === '/api/admin/referral/relationship-history' && call.query === '?customer_id=101&limit=50'), 'history must query only the selected trusted customer');
const awardsTab = [...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '人工发奖'); awardsTab.click();
await waitFor(() => dom.window.document.body.textContent.includes('待核查'), 'manual award needs-review state must be visible to the operator');
assert.match(dom.window.document.body.textContent, /周榜（2026-W38，北京时间）/, 'stored award periods must be presented in Chinese with their Beijing scope');
[...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '登记人工发奖').click();
const awardDialog = dom.window.document.querySelector('[data-testid="referral-admin-dialog"]');
assert.equal(awardDialog.textContent.includes('计分事实'), false, 'award form must not expose internal score event IDs');
const awardPeriod = awardDialog.querySelector('select[name="榜单周期"]');
assert.deepEqual([...awardPeriod.options].map((option) => option.value), ['total', 'day', 'week'], 'award period must use constrained business choices');
awardPeriod.value = 'week'; awardPeriod.dispatchEvent(new dom.window.Event('change', { bubbles: true }));
const awardDate = awardDialog.querySelector('input[name="榜单日期（北京时间）"]'); awardDate.value = '2026-09-18';
awardDialog.querySelector('input[name="奖励内容"]').value = '周榜奖品'; awardDialog.querySelector('input[name="处理凭证"]').value = 'proof-week';
const awardSearch = awardDialog.querySelector('input[type=search]'); awardSearch.value = '可信'; [...awardDialog.querySelectorAll('button')].find((button) => button.textContent === '搜索客户').click();
await waitFor(() => [...awardDialog.querySelectorAll('button')].some((button) => button.textContent === '可信客户'), 'award winner picker did not use the authorized customer directory');
[...awardDialog.querySelectorAll('button')].find((button) => button.textContent === '可信客户').click();
[...awardDialog.querySelectorAll('button')].find((button) => button.textContent === '登记发奖').click();
await waitFor(() => calls.some((call) => call.path === '/api/admin/referral/rewards' && call.method === 'POST'), 'award write did not call the Referral endpoint');
assert.deepEqual(JSON.parse(calls.find((call) => call.path === '/api/admin/referral/rewards' && call.method === 'POST').body), { campaign_id: 7, customer_id: 101, score_event_id: 0, period: 'week:2026-W38', reward: '周榜奖品', evidence_reference: 'proof-week' }, 'award must serialize a Beijing business period and no internal score-event selection');
const participantsTab = [...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '参与记录'); participantsTab.click();
await waitFor(() => dom.window.document.body.textContent.includes('无邀请来源'), 'direct participation must be labelled as having no invitation source');
assert.equal([...dom.window.document.querySelectorAll('button')].filter((button) => button.textContent === '撤销').length, 1, 'only a valid score may offer the reversal operation');
[...dom.window.document.querySelectorAll('button')].find((button) => button.textContent === '撤销').click();
const revokeDialog = dom.window.document.querySelector('[data-testid="referral-admin-dialog"]');
revokeDialog.querySelector('input[name="撤销原因"]').value = '重复授权';
[...revokeDialog.querySelectorAll('button')].find((button) => button.textContent === '确认撤销').click();
await waitFor(() => calls.some((call) => call.path === '/api/admin/referral/participations/12/reverse' && call.method === 'POST'), 'numeric participation ID must be used in the reversal route');
assert.deepEqual(JSON.parse(calls.find((call) => call.path === '/api/admin/referral/participations/12/reverse').body), { reason: '重复授权' }, 'reversal body must keep the operator reason only');
dom.window.close();
console.log('referralAdmin behavior passed');
