import assert from 'node:assert/strict';
import fs from 'node:fs';
import { fileURLToPath } from 'node:url';
import { JSDOM } from 'jsdom';
import { buildTestBrowserBundle } from '../scripts/test-browser-bundle.mjs';
const bundle = await buildTestBrowserBundle(fileURLToPath(new URL('./referralAdmin.ts', import.meta.url)));
const picker = fs.readFileSync(new URL('../../internal/webshell/static/admin_console/admin_search_select.js', import.meta.url),'utf8');
const json = body => new Response(JSON.stringify(body),{status:200,headers:{'Content-Type':'application/json'}});
const wait = async fn => { for(let i=0;i<150;i++){if(fn())return;await new Promise(r=>setTimeout(r,10));} throw new Error('UI did not settle'); };
for(const active of [false,true]) {
 const writes=[];
 const campaign={id:2,name:'购买活动',state:active?'active':'draft',effective_state:active?'active':'draft',starts_at:active?'2026-01-01T00:00:12Z':'2099-01-01T00:00:12Z',ends_at:'2099-12-01T00:00:12Z',version:2,team_mode:'individual',qualification_mode:'product_purchase',product_id:51,product_type:'standard_product',leaderboard_metric:'sales_amount',description:'介绍',reward_rules:'奖励'};
 const dom=new JSDOM('<section id="referral-admin-root"></section>',{url:'https://crm.example/admin/referral/settings?campaign=2',runScripts:'dangerously',beforeParse(w){ w.Headers=Headers; w.Response=Response; w.fetch=async (input,init={})=>{ const u=new URL(String(input),'https://crm.example'); if(init.method==='PUT'){writes.push(JSON.parse(init.body));return json({...campaign,...writes.at(-1),version:3});} if(u.pathname.endsWith('/product-options'))return json({items:[{id:51,code:'122331',name:'测试',product_type:'standard_product'}],total:1}); if(u.pathname.endsWith('/campaigns'))return json({items:[campaign]}); if(u.pathname.endsWith('/campaigns/2'))return json(campaign);return json({items:[]});}; }});
 dom.window.eval(picker); dom.window.eval(bundle);
 await wait(()=>dom.window.document.querySelector('[data-testid="referral-admin-settings-page"]'));
 const doc=dom.window.document;
 await wait(()=>doc.body.textContent.includes('122331'));
 assert.equal(doc.querySelector('dialog'),null);
 assert.equal(doc.querySelector('[aria-label="资格商品"]').value,'51:standard_product');
 assert.equal(doc.querySelector('select[name="战队模式"]').value,'individual');
 assert.equal(doc.querySelector('select[name="参加条件"]').disabled,active);
 doc.querySelector('textarea[name="活动介绍"]').value='新介绍';
 doc.querySelector('[data-testid="referral-admin-save-campaign"]').click();
 await wait(()=>writes.length===1);
 assert.equal(writes[0].qualification_mode,'product_purchase'); assert.equal(writes[0].product_id,51); assert.equal(writes[0].team_mode,'individual'); assert.equal(writes[0].description,'新介绍');
 if(active)assert.equal(writes[0].starts_at,campaign.starts_at,'locked timestamp seconds must remain exact');
 await wait(()=>dom.window.location.pathname==='/admin/referral');
 dom.window.close();
}
console.log('referral settings route, product selection, active copy save and readback passed');
